name: Devops lab workflow

on:
  workflow_dispatch: # allows manual trigger from GitHub UI

jobs:
  echo-steps:
    runs-on: ubuntu-latest

    steps:
      - name: First step
        run: echo "this is the first step"

      - name: Second step
        run: echo "this is the second step"